### ISSUE TITLE
Questions for MPV-INF

### ISSUE THREAD

**Issue by rafael** [code-for-venezuela/2019-april-codeathon#25]
From @brirams  review: 

## Questions

- do we need a specific format for storing or do we have free reign?
- one thing that's probably needed: an api for visualization
- as mentioned, this is a big one. project 1-3 can be done by 2 people each so call this 3 small challenges

**Comment by gustavoatt** [comment]
Thanks @brirams for the help 🚀. Here are some thoughts/questions I have about each point before I go ahead and modify MPV-INF description. 

1. **Specific format for storing**: I don't think we should impose a specific format, as long as it is an open format. Probably a gziped JSON or CSV would be the easiest since there are many tools that support these two formats.
2. **API for visualization**:  @brirams @rafael what do you mean by this? Do you mean an API that the visualization tool can use to fetch its data?
3. **Challenges split**: we do specify that these are indeed 3 challenges. Do you think we should split and create 3 documents, one for each challenge? Main reason about having in a single file is so that the context is easily understood.
